version: '2'
services:
  front:
    build: ./front
    ports:
      - "3333:3333"
    volumes:
      - ./front:/app
  receiver:
    build: ./receiver
    env_file:
      - ./receiver.env
    ports:
      - "3334:3333"
    volumes:
      - ./receiver/app:/app
    extra_hosts:
      - "localhost.firebaseio.test:0.0.0.0"